
name: sdk-version

on:
  push

jobs:
  test-run:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: idleberg/setup-playdate-sdk@main
      with:
        sdk-version: '1.11.1'

    - name: Test version match
      run: |
        if pdc --version | grep -q '1.11.1'; then
          exit 0
        fi

        echo "Version mismatch"
        exit 1
