
name: test:sdk-version

on:
  push

jobs:
  test-run:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: ['1.10.0', '1.11.0']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: idleberg/setup-playdate-sdk@main
      with:
        sdk-version: ${{ matrix.version }}

    - name: Test version match
      run: |
        if pdc --version | grep -q ${{ matrix.version }}; then
          exit 0
        fi

        echo "Version mismatch"
        exit 1
