
name: sdk-version:1.11.1

on:
  push

jobs:
  test-run:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: idleberg/setup-playdate-sdk@main
      with:
        sdk-version: '1.11.1'

    - name: Test environment variable
      run: |
        if [ -z "${PLAYDATE_SDK_PATH}" ]; then
          echo "PLAYDATE_SDK_PATH is not defined or empty"
          exit 1
        fi

        $PLAYDATE_SDK_PATH/bin/pdc --version

    - name: Test version match
      run: |
        if pdc --version | grep -q '1.11.1'; then
          exit 0
        fi

        echo "Version mismatch"
        exit 1
